api/urls.py
from django.urls import path

from . import views

app_name = 'api'

urlpatterns = [
    path('comingsoondata', views.ComingsoonData.as_view(), name="comingsoondata"),
    path('joinclubdata', views.JoinclubData.as_view(), name="joinclubdata"),
    path('receiveprizedata', views.ReceiveprizeData.as_view(), name="receiveprizedata"),
    path('attendancedata', views.AttendanceData.as_view(), name="attendancedata"),
]

chart/urls.py
from django.urls import path

from . import views

app_name = 'chart'

urlpatterns = [
    path('joinclub', views.joinclub, name="joinclub"),
    path('receiveprize', views.receiveprize, name="receiveprize"),
    path('attendance', views.attendance, name="attendance"),
    path('export_all', views.export_all, name="export_all"),
    path('export_NP', views.export_NP, name="export_NP"),
    path('export_M', views.export_M, name="export_M"),
    path('export_secret', views.export_secret, name="export_secret"),
]

joinclub/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('comingsoon/', views.comingsoon, name="comingsoon"),
    path('course/', views.course, name="course"),
    #path('admin/', admin.site.urls),
    path('nimda_ognajd/', admin.site.urls), # django_admin倒過來
    path('join/', include('join.urls')),
    path('chart/', include('chart.urls')),
    path('enter/', include('enter.urls')),
    path('api/', include('api.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

handler400 = views.error_400
handler403 = views.error_403
handler404 = views.error_404
handler500 = views.error_500

chart/models.py
from django.db import models

# Create your models here.

chart/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.utils.http import urlquote
import csv, codecs
from join.models import Member, secret

@login_required
def joinclub(request):
    return render(request, 'joinclub.html', {})

@login_required
def receiveprize(request):
    return render(request, 'receiveprize.html', {})

@login_required
def attendance(request):
    return render(request, 'attendance.html', {})

@login_required
def export_all(request):
    members = Member.objects.all()
    response = HttpResponse(content_type='text/csv')
    response.write(codecs.BOM_UTF8)
    response['Content-Disposition'] = 'attachment; filename="%s"' %(urlquote("社員資料.csv"))
    writer = csv.writer(response)
    writer.writerow(['姓名', '學號', '系級', '年級', '手機號碼', '電子郵件', '付款方式', '銀行末五碼', '學校', '外校名稱', 'Discord ID', '社服尺寸', '收據編號', '入社狀態'])
    for member in members:
        writer.writerow([member.name, member.nid, member.dept, member.level, member.phone, member.email, member.get_pay_display(), member.bankAccount, member.get_is_FCU_display(), member.school, member.DiscordId, member.get_clothes_display(), member.receiptNumber, member.get_status_display()])
    return response

@login_required
def export_M(request):
    members = Member.objects.filter(status='M')
    response = HttpResponse(content_type='text/csv')
    response.write(codecs.BOM_UTF8)
    response['Content-Disposition'] = 'attachment; filename="%s"' %(urlquote("社員資料(已繳費).csv"))
    writer = csv.writer(response)
    writer.writerow(['姓名', '學號', '系級', '年級', '手機號碼', '電子郵件', '付款方式', '銀行末五碼', '學校', '外校名稱', 'Discord ID', '社服尺寸', '收據編號', '入社狀態'])
    for member in members:
        writer.writerow([member.name, member.nid, member.dept, member.level, member.phone, member.email, member.get_pay_display(), member.bankAccount, member.get_is_FCU_display(), member.school, member.DiscordId, member.get_clothes_display(), member.receiptNumber, member.get_status_display()])
    return response

@login_required
def export_NP(request):
    members = Member.objects.filter(status='NP')
    response = HttpResponse(content_type='text/csv')
    response.write(codecs.BOM_UTF8)
    response['Content-Disposition'] = 'attachment; filename="%s"' %(urlquote("社員資料(未繳費).csv"))
    writer = csv.writer(response)
    writer.writerow(['姓名', '學號', '系級', '年級', '手機號碼', '電子郵件', '付款方式', '銀行末五碼', '學校', '外校名稱', 'Discord ID', '社服尺寸', '收據編號', '入社狀態'])
    for member in members:
        writer.writerow([member.name, member.nid, member.dept, member.level, member.phone, member.email, member.get_pay_display(), member.bankAccount, member.get_is_FCU_display(), member.school, member.DiscordId, member.get_clothes_display(), member.receiptNumber, member.get_status_display()])
    return response


@login_required
def export_secret(request):
    members = secret.objects.all()
    response = HttpResponse(content_type='text/csv')
    response.write(codecs.BOM_UTF8)
    response['Content-Disposition'] = 'attachment; filename="%s"' % (
        urlquote("保密協議名單.csv"))
    writer = csv.writer(response)
    writer.writerow(['姓名', '學號', '手機號碼'])
    for member in members:
        writer.writerow([member.name, member.nid, member.phone])
    return response

joinclub/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html', {})

def comingsoon(request):
    return render(request, 'comingsoon.html', {})

def course(request):
    return render(request, 'course.html', {})

def error_400(request, exception):
    return render(request,'errors/400.html', {})

def error_403(request, exception):
    return render(request,'errors/403.html', {})

def error_404(request, exception):
    return render(request,'errors/404.html', {})

def error_500(request):
    return render(request,'errors/500.html', {})

def csrf_failure(request, reason=""):
    return render(request,'errors/403_csrf.html', {})

chart/templates/attendance.html
{% extends "layout.html" %}

{% block title %}黑客社 - 出席情形{% endblock %}

{% block content %}
<div class="container" id="content">
    <div class="row">
        <div class="col-sm-6 my-2">
            <div class="card text-center border-info">
                <div class="card-header">
                    <h4 class="my-0">事前調查總人數</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title" id="Attend_count"></h1>
                </div>
            </div>
        </div>
        <div class="col-sm-6 my-2">
            <div class="card text-center border-primary">
                <div class="card-header">
                    <h4 class="my-0">事前調查出席人數</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title" id="Count"></h1>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div id="chart"></div>
</div>
{% endblock %}

{% block js %}
<!-- Plotly.js -->
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

<script type="text/javascript">
    var interval = null;

    $(document).ready(function ($) {
        refresh();
        interval = setInterval("refresh()", 10000);
    });

    function refresh() {
        $.ajax({
            url: "{% url 'api:attendancedata' %}",
            type: "get",
            dataType:  "json",
            success: function(data) {
                document.getElementById("Attend_count").innerHTML = data["Attend_count"];
                document.getElementById("Count").innerHTML = data["Count"];
                var one = data["Attend_count"] - data["Count"]
                var data = [{
                    values: [one, data["Count"]],
                    labels: ['未出席', '出席'],
                    type: 'pie'
                }];
                var layout = {
                    title: '事前調查出席人數',
                };
                Plotly.newPlot('chart', data, layout, {responsive: true});
            },
            error: function() {
                clearInterval(interval);
                var alert =  '<div class="alert alert-danger alert-dismissible fade show" role="alert">'+
                                '<h4 class="alert-heading">發生錯誤</h4>'+
                                '<p>無法更新資訊，請檢查您的網路狀態</p>'+
                                '<p>或是<a href="javascript:location.reload(true)" class="alert-link">點此重新整理您的頁面</a></p>'+
                                '<hr>'+
                                '<p>'+
                                    '若無法解決，請聯絡<big><a href="https://www.facebook.com/HackerSir.tw/" target="_blank">逢甲大學黑客社</a></big>，並闡述您所遭遇的狀況。'+
                                '</p>'+
                                '<button type="button" class="close" data-dismiss="alert" aria-label="Close">'+
                                    '<span aria-hidden="true">&times;</span>'+
                                '</button>'+
                            '</div>';
                document.getElementById("content").insertAdjacentHTML('afterbegin', alert);
            }
        });
    }
</script>
{% endblock %}

chart/templates/joinclub.html
{% extends "layout.html" %}

{% block title %}黑客社 - 入社情形{% endblock %}

{% block content %}
<div class="container" id="content">
    <div class="row">
        <div class="col-sm-4 my-2">
            <div class="card text-center border-info">
                <div class="card-header">
                    <h4 class="my-0">與會人數</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title" id="Checkin_count"></h1>
                </div>
            </div>
        </div>
        <div class="col-sm-4 my-2">
            <div class="card text-center border-primary">
                <div class="card-header">
                    <h4 class="my-0">填表總人數</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title" id="Member_count"></h1>
                </div>
            </div>
        </div>
        <div class="col-sm-4 my-2">
            <div class="card text-center border-success">
                <div class="card-header">
                    <h4 class="my-0">已入社人數</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title" id="M_count"></h1>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div id="chart"></div>
</div>
{% endblock %}

{% block js %}
<!-- Plotly.js -->
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

<script type="text/javascript">
    var interval = null;

    $(document).ready(function ($) {
        refresh();
        interval = setInterval("refresh()", 10000);
    });

    function refresh() {
        $.ajax({
            url: "{% url 'api:joinclubdata' %}",
            type: "get",
            dataType:  "json",
            success: function(data) {
                document.getElementById("Checkin_count").innerHTML = data["Checkin_count"];
                document.getElementById("Member_count").innerHTML = data["Member_count"];
                document.getElementById("M_count").innerHTML = data["M_count"];
                var one = data["Checkin_count"] - data["Member_count"]
                var two = data["Member_count"] - data["M_count"]
                var data = [{
                    values: [one, two, data["M_count"]],
                    labels: ['未填表人數', '已填表未入社人數', '已入社人數'],
                    type: 'pie'
                }];
                var layout = {
                    title: '入社情況',
                };
                Plotly.newPlot('chart', data, layout, {responsive: true});
            },
            error: function() {
                clearInterval(interval);
                var alert =  '<div class="alert alert-danger alert-dismissible fade show" role="alert">'+
                                '<h4 class="alert-heading">發生錯誤</h4>'+
                                '<p>無法更新資訊，請檢查您的網路狀態</p>'+
                                '<p>或是<a href="javascript:location.reload(true)" class="alert-link">點此重新整理您的頁面</a></p>'+
                                '<hr>'+
                                '<p>'+
                                    '若無法解決，請聯絡<big><a href="https://www.facebook.com/HackerSir.tw/" target="_blank">逢甲大學黑客社</a></big>，並闡述您所遭遇的狀況。'+
                                '</p>'+
                                '<button type="button" class="close" data-dismiss="alert" aria-label="Close">'+
                                    '<span aria-hidden="true">&times;</span>'+
                                '</button>'+
                            '</div>';
                document.getElementById("content").insertAdjacentHTML('afterbegin', alert);
            }
        });
    }
</script>
{% endblock %}

chart/templates/receiveprize.html
{% extends "layout.html" %}

{% block title %}黑客社 - 領獎情形{% endblock %}

{% block content %}
<div class="container" id="content">
    <div class="row">
        <div class="col-sm-6 my-2">
            <div class="card text-center border-info">
                <div class="card-header">
                    <h4 class="my-0">與會人數</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title" id="Checkin_count"></h1>
                </div>
            </div>
        </div>
        <div class="col-sm-6 my-2">
            <div class="card text-center border-success">
                <div class="card-header">
                    <h4 class="my-0">已領獎</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title" id="Prize_count"></h1>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div id="chart"></div>
</div>
{% endblock %}

{% block js %}
<!-- Plotly.js -->
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

<script type="text/javascript">
    var interval = null;

    $(document).ready(function ($) {
        refresh();
        interval = setInterval("refresh()", 10000);
    });

    function refresh() {
        $.ajax({
            url: "{% url 'api:receiveprizedata' %}",
            type: "get",
            dataType:  "json",
            success: function(data) {
                document.getElementById("Checkin_count").innerHTML = data["Checkin_count"];
                document.getElementById("Prize_count").innerHTML = data["Prize_count"];
                var one = data["Checkin_count"] - data["Prize_count"]
                var data = [{
                    values: [one, data["Prize_count"]],
                    labels: ['未領獎', '已領獎'],
                    type: 'pie'
                }];
                var layout = {
                    title: '領獎情形',
                };
                Plotly.newPlot('chart', data, layout, {responsive: true});
            },
            error: function() {
                clearInterval(interval);
                var alert =  '<div class="alert alert-danger alert-dismissible fade show" role="alert">'+
                                '<h4 class="alert-heading">發生錯誤</h4>'+
                                '<p>無法更新資訊，請檢查您的網路狀態</p>'+
                                '<p>或是<a href="javascript:location.reload(true)" class="alert-link">點此重新整理您的頁面</a></p>'+
                                '<hr>'+
                                '<p>'+
                                    '若無法解決，請聯絡<big><a href="https://www.facebook.com/HackerSir.tw/" target="_blank">逢甲大學黑客社</a></big>，並闡述您所遭遇的狀況。'+
                                '</p>'+
                                '<button type="button" class="close" data-dismiss="alert" aria-label="Close">'+
                                    '<span aria-hidden="true">&times;</span>'+
                                '</button>'+
                            '</div>';
                document.getElementById("content").insertAdjacentHTML('afterbegin', alert);
            }
        });
    }
</script>
{% endblock %}