api/urls.py
from django.urls import path

from . import views

app_name = 'api'

urlpatterns = [
    path('comingsoondata', views.ComingsoonData.as_view(), name="comingsoondata"),
    path('joinclubdata', views.JoinclubData.as_view(), name="joinclubdata"),
    path('receiveprizedata', views.ReceiveprizeData.as_view(), name="receiveprizedata"),
    path('attendancedata', views.AttendanceData.as_view(), name="attendancedata"),
]

chart/urls.py
from django.urls import path

from . import views

app_name = 'chart'

urlpatterns = [
    path('joinclub', views.joinclub, name="joinclub"),
    path('receiveprize', views.receiveprize, name="receiveprize"),
    path('attendance', views.attendance, name="attendance"),
    path('export_all', views.export_all, name="export_all"),
    path('export_NP', views.export_NP, name="export_NP"),
    path('export_M', views.export_M, name="export_M"),
    path('export_secret', views.export_secret, name="export_secret"),
]

enter/urls.py
from django.urls import path

from . import views

app_name = 'enter'

urlpatterns = [
    path('attend', views.attend, name="attend"),
    path('search', views.search, name="search"),
    path('edit/<int:id>', views.edit, name="edit"),
    path('checkin', views.checkin, name="checkin"),
    path('prize/<str:nid>', views.prize, name="prize"),
]

join/urls.py
from django.urls import path

from . import views

app_name = 'join'

urlpatterns = [
    path('join', views.join, name="join"),
    path('secret', views.join_secret, name="secret"),
    path('search', views.search, name="search"),
    path('secretSearch', views.secretSearch, name="secretSearch"),
    path('searchForMember', views.searchForMember, name="searchForMember"),
    path('send_email/<int:id>', views.send_email, name="send_email"),
    path('review/<int:id>', views.review, name="review"),
    path('edit/<int:id>', views.edit, name="edit"),
    path('view', views.view, name="view"),
]

joinclub/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('comingsoon/', views.comingsoon, name="comingsoon"),
    path('course/', views.course, name="course"),
    #path('admin/', admin.site.urls),
    path('nimda_ognajd/', admin.site.urls), # django_admin倒過來
    path('join/', include('join.urls')),
    path('chart/', include('chart.urls')),
    path('enter/', include('enter.urls')),
    path('api/', include('api.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

handler400 = views.error_400
handler403 = views.error_403
handler404 = views.error_404
handler500 = views.error_500

join/models.py
from typing import Counter
from django.db import models


class Member(models.Model):
    LEVEL_CHOICES = [
        ('B1', '大一'),
        ('B2', '大二'),
        ('B3', '大三'),
        ('B4', '大四'),
        ('M1', '碩一'),
        ('M2', '碩二'),
    ]

    STATUS_CHOICES = [
        ('NP', '未付款'),
        ('M', '已入社'),
    ]

    PAY_CHOICES = [
        ('C', '現金'),
        ('R', '匯款'),
    ]

    SCHOOL_CHOICES = [
        ('Y', '逢甲大學'),
        ('N', '其他學校'),
    ]

    CLOTHES_CHOICES = [
        ('N', '不購買'),
        ('XXS', '尺寸 XXS'),
        ('XS', '尺寸 XS'),
        ('S', '尺寸 S'),
        ('M', '尺寸 M'),
        ('L', '尺寸 L'),
        ('XL', '尺寸 XL'),
        ('2XL', '尺寸 2XL'),
    ]

    name = models.CharField(max_length=50)
    nid = models.CharField(max_length=15, unique=True)
    dept = models.CharField(max_length=20)
    level = models.CharField(max_length=2, choices=LEVEL_CHOICES, default='B1')
    # 不能用 unique=True，因為空字串也會被判斷成一樣
    phone = models.CharField(max_length=15, null=True, unique=True)
    email = models.EmailField(unique=True)
    status = models.CharField(max_length=2, choices=STATUS_CHOICES, default="NP")
    pay = models.CharField(max_length=2, choices=PAY_CHOICES, default="C")
    bankAccount = models.CharField(max_length=5, null=True, blank=True)
    is_FCU = models.CharField(max_length=5, choices=SCHOOL_CHOICES,default="Y")
    school = models.CharField(max_length=50, blank=True)
    DiscordId = models.CharField(max_length=50, null=True)
    clothes = models.CharField(max_length=4, choices=CLOTHES_CHOICES, default='N')
    receiptNumber = models.IntegerField(default=0)  # 收據編號
    # created_at = models.DateTimeField(auto_now_add=True) # 入社表單填寫時間 給下一屆用
    def __str__(self):
        return "%s %s [%s]" % (self.nid, self.name, self.get_status_display())


class secret(models.Model):
    """
    保密協議
    """
    name = models.CharField(max_length=50)
    nid = models.CharField(max_length=15, unique=True)
    phone = models.CharField(max_length=15, null=True, unique=True)
    create_time = models.DateTimeField(auto_now_add=True)

class receipt(models.Model):
    """
    紀錄收據的編號
    """
    FCUcount = models.IntegerField() # 校內
    offFCUcount = models.IntegerField() # 校外

join/forms.py
from django import forms
from django.forms import ModelForm, fields, models
from django.utils.translation import gettext_lazy as _
from .models import Member, secret
import re

LEVEL_CHOICES = (
    ('B1', '大一'),
    ('B2', '大二'),
    ('B3', '大三'),
    ('B4', '大四'),
    ('M1', '碩一'),
    ('M2', '碩二')
)


class JoinForm(ModelForm):
    #agree1 = forms.CharField(widget=forms.widgets.CheckboxInput(), max_length=3, required=True, label='123', error_messages={'required':'test3'})
    class Meta:
        model = Member
        fields = ['name', 'nid', 'dept', 'level',
                  'phone', 'email', 'pay', 'bankAccount', 'is_FCU', 'school', 'DiscordId',]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '請輸入姓名'}),
            'nid': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '請輸入學號'}),
            'dept': forms.TextInput(attrs={'class': 'form-control', 'aria-describedby': 'deptHelp', 'placeholder': '請輸入系級'}),
            'level': forms.Select(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'aria-describedby': 'phoneHelp', 'placeholder': '請輸入電話號碼'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'aria-describedby': 'emailHelp', 'placeholder': '請輸入電子郵件'}),
            'pay': forms.Select(attrs={'class': 'form-control'}),
            'bankAccount': forms.TextInput(attrs={'class': 'form-control', 'aria-describedby': 'bankAccountHelp', 'placeholder': '請輸入銀行末五碼'}),
            'is_FCU': forms.Select(attrs={'class': 'form-control'}),
            'school': forms.TextInput(attrs={'class': 'form-control', 'aria-describedby': 'schoolHelp', 'placeholder': '如果您不是逢甲大學學生，請輸入您的學校名稱'}),
            'DiscordId': forms.TextInput(attrs={'class': 'form-control', 'aria-describedby': 'DiscodeIdHelp', 'placeholder': '請輸入您的 Discord ID'}),
            # 'clothes': forms.Select(attrs={'class': 'form-control'}),
        }
        labels = {
            'name': _('姓名'),
            'nid': _('學號'),
            'dept': _('系級'),
            'level': _('年級'),
            'phone': _('電話'),
            'email': _('E-mail'),
            'pay': _('付款方式'),
            'bankAccount': _('銀行末五碼'),
            'is_FCU': _('學校'),
            'school': _('外校名稱'),
            'DiscordId': _('Discord ID'),
            # 'clothes': _('社服尺寸'),
        }
        help_texts = {
            'dept': _('例如：資訊一甲'),
            'phone': _('請輸入可以聯絡到您的手機'),
            'email': _('請輸入您常用的 E-mail'),
            'bankAccount': _('付款方式選擇匯款才需要填'),
            'school': _('學校選擇其他學校才需要填'),
            'DiscordId': _('例如：meow#1234'),
        }
        error_messages = {
            'name': {
                'required': _('必須填寫姓名'),
                'max_length': _('你的姓名太長囉'),
            },
            'nid': {
                'required': _('必須填寫學號'),
                'unique': _('您的學號已經被使用過囉'),
                'max_length': _('你的學號太長囉'),
            },
            'dept': {
                'required': _('必須填寫系級'),
                'max_length': _('你的系級太長囉'),
            },
            'level': {
                'required': _('必須選擇年級'),
                'invalid_choice': _('請勿亂來'),
            },
            'phone': {
                'required': _('必須填寫電話'),
                'max_length': _('你的電話太長囉'),
                'unique': _('您的手機號碼已經被使用過囉'),
            },
            'email': {
                'required': _('必須填寫 E-mail'),
                'unique': _('您的 Email 已經被使用過囉'),
                'invalid': _('您的 E-mail 看起來怪怪的喔')
            },
            'pay': {
                'required': _('必須選擇付款方式'),
                'invalid_choice': _('請勿亂來'),
            },
            'bankAccount': {
                'max_length': _('您的系級太長囉'),
            },
            'is_FCU': {
                'required': _('必須選擇學校'),
                'invalid_choice': _('請勿亂來'),
            },
            'school': {
                'max_length': _('您的學校名稱太長囉'),
            },
            'DiscordId': {
                'max_length': _('您的 Discord ID 太長囉'),
            },
            # 'clothes': {
            #     'required': _('必須選擇社服尺寸'),
            #     'invalid_choice': _('請勿亂來'),
            # },
        }
    def clean_nid(self):
        # nid欄位全部大寫
        nid = self.cleaned_data['nid']
        return nid.upper()


class secretForm(ModelForm):

    class Meta:
        model = secret
        fields = ['name', 'nid', 'phone']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '請輸入姓名'}),
            'nid': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '請輸入學號'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'aria-describedby': 'phoneHelp', 'placeholder': '請輸入電話號碼'}),
        }
        labels = {
            'name': _('姓名'),
            'nid': _('學號'),
            'phone': _('電話'),
        }
        help_texts = {
            'phone': _('請輸入可以聯絡到您的手機'),
        }
        error_messages = {
            'name': {
                'required': _('必須填寫姓名'),
                'max_length': _('你的姓名太長囉'),
            },
            'nid': {
                'required': _('必須填寫學號'),
                'unique': _('您的學號已經被使用過囉'),
                'max_length': _('你的學號太長囉'),
            },
            'phone': {
                'max_length': _('你的電話太長囉'),
                'unique': _('您的手機號碼已經被使用過囉'),
            },
        }

join/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models.query_utils import Q
from .forms import JoinForm, secretForm
from .models import Member, secret, receipt
from enter.models import Attend
from .mail import word, mail
import datetime
import os


def join(request):
    if request.method == 'POST':
        form = JoinForm(request.POST)
        if form.is_valid():

            form.save()

            messages.add_message(request, messages.SUCCESS,
                                 '提交成功', extra_tags='joinform')
            return HttpResponseRedirect(reverse('index'))
    else:
        form = JoinForm()
    return render(request, 'join.html', {'form': form})


def join_secret(request):
    """
    填寫保密協議表單
    """
    if request.method == 'POST':
        form = secretForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS,
                                 '提交成功', extra_tags='secretform')
            return HttpResponseRedirect(reverse('index'))
    else:
        form = secretForm()
    return render(request, 'secretForm.html', {'form': form})


def searchForMember(request):
    """
    給社員們用來查詢自己的繳費情形
    """
    if request.method == 'POST':
        nid = request.POST.get('nid')
        if nid:
            try:
                member = Member.objects.get(nid=nid)
                return render(request, 'searchForMember.html', {'member': member})
            except Member.DoesNotExist:
                return render(request, 'searchForMember.html', {'result': '無搜尋結果'})
    return render(request, 'searchForMember.html', {})


@login_required
def search(request):
    """
    admin搜尋入社表單
    """
    if request.method == 'POST':
        searchTerm = request.POST.get('searchTerm')
        # 搜尋大雜燴 一個關鍵字 全部欄位都搜尋
        members = Member.objects.filter(Q(name__icontains=searchTerm) |
                                        Q(nid__icontains=searchTerm) |
                                        Q(dept__icontains=searchTerm) |
                                        Q(phone__icontains=searchTerm) |
                                        #Q(email__icontains=searchTerm) |
                                        Q(bankAccount__icontains=searchTerm) |
                                        #Q(DiscordId__icontains=searchTerm) |
                                        Q(clothes__icontains=searchTerm)
                                        )
        context = {'members': members}
        return render(request, 'join_search.html', context)
    return render(request, 'join_search.html', {})


@login_required
def secretSearch(request):
    """
    admin搜尋保密協議
    """
    if request.method == 'POST':
        searchTerm = request.POST.get('searchTerm')

        # 搜尋大雜燴 一個關鍵字 全部欄位都搜尋
        secrets = secret.objects.filter(Q(name__icontains=searchTerm) |
                                        Q(nid__icontains=searchTerm) |
                                        Q(phone__icontains=searchTerm))
        try:
            # 條碼機刷學生證會多一位數
            Temp = searchTerm
            if len(searchTerm) == 9:
                Temp = searchTerm[0:-1]
            secretResult = secret.objects.get(nid__iexact=Temp)
            context = {'secret': secretResult, 'secrets': secrets}
            return render(request, 'secret_search.html', context)
        except secret.DoesNotExist:
            context = {'secrets': secrets, 'searchTerm': searchTerm}
            return render(request, 'secret_search.html', context)

    return render(request, 'secret_search.html', {})


@login_required
def send_email(request, id):
    '''
    繳費完成後，寄送收據給社員
    '''
    member = get_object_or_404(Member, id=id)
    path = os.path.join('Receipt', '社費')
    if member.is_FCU == 'N':  # 校外學生
        file1 = os.path.join(path, '社員收執', '11010107' +
                             str(member.receiptNumber).zfill(3) + '.pdf')
        file2 = os.path.join(path, '社團存根', '11010107' +
                             str(member.receiptNumber).zfill(3) + '.pdf')
    else:
        file1 = os.path.join(path, '社員收執', '11010101' +
                             str(member.receiptNumber).zfill(3) + '.pdf')
        file2 = os.path.join(path, '社團存根', '11010101' +
                             str(member.receiptNumber).zfill(3) + '.pdf')
    if os.path.isfile(file1) == False or os.path.isfile(file2) == False:
        if member.receiptNumber == 0:
            Receipt = receipt.objects.all()
            if len(Receipt) == 0:
                receipt.objects.create(FCUcount=0, offFCUcount=0)
                Receipt = receipt.objects.all()
            receiptTmp = Receipt[0]
            if member.is_FCU == 'N':  # 校外學生
                receiptTmp.offFCUcount += 1
                member.receiptNumber = receiptTmp.offFCUcount
            else:
                receiptTmp.FCUcount += 1
                member.receiptNumber = receiptTmp.FCUcount
            receiptTmp.save()
            member.save()
        time_now = datetime.datetime.now().strftime("%Y-%m-%d")
        word(member.name, member.nid, time_now,
             member.receiptNumber, member.is_FCU)

    try:
        mail(member.name, member.nid, member.is_FCU,
             member.email, member.receiptNumber)
    except FileNotFoundError:   # Libre 一次產生大量pdf好像會有BUG 先這樣寫
        return redirect('join:review', id)
    member.status = 'M'  # 社員狀態改為已入社
    member.save()
    return redirect('join:review', id)


@login_required
def review(request, id):
    member = get_object_or_404(Member, id=id)
    if request.method == 'POST':
        if member.status == 'NP':
            # 先寄送電子收據 再把狀態改為已入社
            return redirect('join:send_email', id)
    return render(request, 'review.html', {'member': member})


@login_required
def edit(request, id):
    member = get_object_or_404(Member, id=id)
    if request.method == 'POST':
        form = JoinForm(request.POST, instance=member)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('join:review', args=[member.id]))
        else:
            return render(request, 'join_edit.html', {'form': form, 'member': member})
    else:
        form = JoinForm()
    return render(request, 'join_edit.html', {'form': form, 'member': member})


@login_required
def view(request):
    M_members = Member.objects.filter(status='M')
    NP_members = Member.objects.filter(status='NP')
    attends = Attend.objects.all()
    return render(request, 'view.html', {'M_members': M_members, 'NP_members': NP_members, 'attends': attends})

join/templates/clothes.html
<!-- 社服尺寸內容 -->
{% load static %}
<div class="modal fade" id="clothesModal" tabindex="-1" role="dialog" aria-labelledby="clothesModalTitle"
aria-hidden="true">
<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="clothesModalTitle"><b>第八屆社服尺寸</b></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

        <div class="modal-body">
            <img class="img-fluid" src="{% static '社服.jpg' %}">
            <img class="img-fluid" src="{% static '社服尺寸.jpg' %}">
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-warning" data-dismiss="modal">
                <i class="fas fa-tshirt"></i>
                確認
            </button>
        </div>
    </div>
</div>
</div>

join/templates/join_search.html
{% extends "layout.html" %}

{% block head %}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.1/css/all.css" integrity="sha384-wxqG4glGB3nlqX0bi23nmgwCSjWIW13BdLUEYC4VIMehfbcro/ATkyDsF/AbIOVe" crossorigin="anonymous">
{% endblock %}

{% block title %}黑客社 - 查詢(入社表單){% endblock %}

{% block content %}
<div class="container">
    <div class="row d-flex justify-content-between">
        <div class="col-auto">
            <h3>入社表單 - 查詢</h3>
        </div>
        <div class="btn-group col-auto">
            <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                匯出 CSV
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'chart:export_all' %}">全部</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'chart:export_M' %}">已繳費</a>
                <a class="dropdown-item" href="{% url 'chart:export_NP' %}">未繳費</a>
            </div>
        </div>
    </div>
    
    <hr>
    <form action="{% url 'join:search' %}" method="POST">
        {% csrf_token %}
        <div class="form-row align-items-center">
            <label class="sr-only" for="nid">NID</label>
            <div class="input-group col-6">
                <div class="input-group-prepend">
                    <div class="input-group-text">入社表單</div>
                </div>
                <input type="text" class="form-control" id="searchTerm" placeholder="輸入學號、姓名、電話" name="searchTerm">
                <div class="input-group-append">
                    <button type="submit" class="btn btn-outline-secondary">
                        <i class="fas fa-search"></i>
                        查詢
                    </button>
                </div>
            </div>
        </div>
    </form>

    <div class="container">
    <table class="table table-striped table-hover ">
    <thead>
        <tr>
        <th scope="col">#</th>
        <th scope="col">姓名</th>
        <th scope="col">學號</th>
        <th scope="col">系級</th>
        <th scope="col">電話</th>
        <th scope="col">付款方式</th>
        <th scope="col">銀行末五碼</th>
        <th scope="col">Discord ID</th>
        <th scope="col">社服尺寸</th>
        <th scope="col">入社情況</th>
        <th scope="col">#</th>
        </tr>
    </thead>
    <tbody>
        {% for member in members %}
        <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td><a href="{% url 'join:review' member.id %}">{{ member.name }}</a></td>
        <td>{{ member.nid }}</td>
        <td>{{ member.dept }}</td>
        <td>{{ member.phone }}</td>
        <td>{{ member.get_pay_display }}</td>
        <td>{{ member.bankAccount }}</td>
        <td>{{ member.DiscordId }}</td>
        <td>{{ member.get_clothes_display }}</td>
        {% comment %} 已入社 {% endcomment %}
        {% ifequal member.status "M" %}
        <td>
            <span class="badge badge-pill badge-success">
                {{ member.get_status_display }}
            </span>
        </td>
        <td>
            <a href="{% url 'join:send_email' id=member.id %}" class="btn btn-success mr-1" role="button">
                <i class="fas fa-hand-holding-usd"></i>
                重新寄送收據
            </a>
        </td>
        {% endifequal %}
        {% comment %} 未付款 {% endcomment %}
        {% ifequal member.status "NP" %}
        <td>
            <span class="badge badge-pill badge-danger">
                {{ member.get_status_display }}
            </span>
        </td>
        <td>
            <form class="form-inline" action="{% url 'join:review' id=member.id %}" method="POST">
                {% csrf_token %}
                {% comment %} 未付款 {% endcomment %}
                <button type="submit" class="btn btn-success mr-1">
                    <i class="fas fa-hand-holding-usd"></i>
                    確認付款
                </button>
            </form>
        </td>
        {% endifequal %}
        </tr>   
        {%endfor%}
    </tbody>
    </table>
</div>
     
</div>
{% endblock %}

join/templates/review.html
{% extends "layout.html" %}

{% block title %}黑客社 - 審核{% endblock %}

{% block content %}
<div class="container">
    <h3>審核</h3>
    <hr>
    <div class="card">
        <h5 class="card-header">
            <div class="row justify-content-between">
                <div class="col-auto">
                    {{ member.nid }} - 社員資料
                </div>
                <div class="col-auto">
                    {% comment %} 已入社 {% endcomment %}
                    {% ifequal member.status "M" %}
                        <span class="badge badge-pill badge-success">
                            {{ member.get_status_display }}
                        </span>
                    {% endifequal %}
                    {% comment %} 未付款 {% endcomment %}
                    {% ifequal member.status "NP" %}
                        <span class="badge badge-pill badge-danger">
                            {{ member.get_status_display }}
                        </span>
                    {% endifequal %}
                </div>
            </div>
        </h5>
        <div class="card-body">
            <p class="card-text">姓名：{{ member.name }}</p>
            <p class="card-text">學號：{{ member.nid }}</p>
            <p class="card-text">系級：{{ member.dept }}</p>
            <p class="card-text">年級：{{ member.get_level_display }}</p>
            <p class="card-text">電話：{{ member.phone }}</p>
            <p class="card-text">E-mail：{{ member.email }}</p>
            <p class="card-text">付款方式：{{ member.get_pay_display }}</p>
            <p class="card-text">銀行末五碼：{{ member.bankAccount }}</p>
            <p class="card-text">學校：{{ member.get_is_FCU_display }}</p>
            <p class="card-text">外校名稱：{{ member.school }}</p>
            <p class="card-text">Discord ID：{{ member.DiscordId }}</p>
            <p class="card-text">社服尺寸：{{ member.get_clothes_display }}</p>
            {% comment %} <p class="card-text">填寫時間：{{ member.created_at }}</p> {% endcomment %}
        </div>
        <div class="card-footer">
            <form class="form-inline" action="{% url 'join:review' id=member.id %}" method="POST">
                {% csrf_token %}
                {% comment %} 未付款 {% endcomment %}
                {% ifequal member.status "NP" %}
                    <button type="submit" class="btn btn-success mr-1">
                        <i class="fas fa-hand-holding-usd"></i>
                        確認付款
                    </button>
                {% endifequal %}
                {% ifequal member.status "M" %}
                    <a href="{% url 'join:send_email' id=member.id %}" class="btn btn-success mr-1" role="button">
                        <i class="fas fa-hand-holding-usd"></i>
                        重新寄送收據
                    </a>
                {% endifequal %}
                <a href="{% url 'join:edit' id=member.id %}" class="btn btn-primary" role="button">
                    <i class="far fa-edit"></i>
                    修改資料
                </a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

join/templates/searchForMember.html
{% extends "layout.html" %}

{% block head %}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.1/css/all.css" integrity="sha384-wxqG4glGB3nlqX0bi23nmgwCSjWIW13BdLUEYC4VIMehfbcro/ATkyDsF/AbIOVe" crossorigin="anonymous">
{% endblock %}

{% block title %}黑客社 - 查詢(入社表單){% endblock %}

{% block content %}
<div class="container">
    <div class="row d-flex justify-content-between">
        <div class="col-auto">
            <h3>繳款情形 - 查詢</h3>
        </div>
        
    </div>
    
    <hr>
    <form action="{% url 'join:searchForMember' %}" method="POST">
        {% csrf_token %}
        <div class="form-row align-items-center">
            <div class="col-auto mr-4">
                <label class="sr-only" for="nid">NID</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text">學號</div>
                    </div>
                    <input type="text" class="form-control" id="nid" placeholder="請輸入欲查詢學號" name="nid">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-outline-secondary">
                            <i class="fas fa-search"></i>
                            查詢
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <br>
    <div class="card">
        <h5 class="card-header">
            <div class="row justify-content-between">
                <div class="col-auto">
                    {% if member.nid %}
                        {{ member.nid }} - 繳款情形
                    {% else %}
                        {{ result }}
                    {% endif %}
                </div>
                <div class="col-auto">
                    {% comment %} 審核中 {% endcomment %}
                    {% ifequal member.status "UR" %}
                        <span class="badge badge-pill badge-info">
                            {{ member.get_status_display }}
                        </span>
                    {% endifequal %}
                    {% comment %} 已入社 {% endcomment %}
                    {% ifequal member.status "M" %}
                        <span class="badge badge-pill badge-success">
                            {{ member.get_status_display }}
                        </span>
                    {% endifequal %}
                    {% comment %} 未付款 {% endcomment %}
                    {% ifequal member.status "NP" %}
                        <span class="badge badge-pill badge-danger">
                            {{ member.get_status_display }}
                        </span>
                    {% endifequal %}
                </div>
            </div>
            
        </h5>
        {% if member.nid %}
            <div class="card-body">
                <div class="col-auto">
                    <p class="card-text">社服尺寸：{{ member.get_clothes_display }}</p>
                </div>
            </div>
        {% endif %}
        
    </div>
    
</div>
{% endblock %}