api/urls.py
from django.urls import path

from . import views

app_name = 'api'

urlpatterns = [
    path('comingsoondata', views.ComingsoonData.as_view(), name="comingsoondata"),
    path('joinclubdata', views.JoinclubData.as_view(), name="joinclubdata"),
    path('receiveprizedata', views.ReceiveprizeData.as_view(), name="receiveprizedata"),
    path('attendancedata', views.AttendanceData.as_view(), name="attendancedata"),
]

chart/urls.py
from django.urls import path

from . import views

app_name = 'chart'

urlpatterns = [
    path('joinclub', views.joinclub, name="joinclub"),
    path('receiveprize', views.receiveprize, name="receiveprize"),
    path('attendance', views.attendance, name="attendance"),
    path('export_all', views.export_all, name="export_all"),
    path('export_NP', views.export_NP, name="export_NP"),
    path('export_M', views.export_M, name="export_M"),
    path('export_secret', views.export_secret, name="export_secret"),
]

enter/urls.py
from django.urls import path

from . import views

app_name = 'enter'

urlpatterns = [
    path('attend', views.attend, name="attend"),
    path('search', views.search, name="search"),
    path('edit/<int:id>', views.edit, name="edit"),
    path('checkin', views.checkin, name="checkin"),
    path('prize/<str:nid>', views.prize, name="prize"),
]

join/urls.py
from django.urls import path

from . import views

app_name = 'join'

urlpatterns = [
    path('join', views.join, name="join"),
    path('secret', views.join_secret, name="secret"),
    path('search', views.search, name="search"),
    path('secretSearch', views.secretSearch, name="secretSearch"),
    path('searchForMember', views.searchForMember, name="searchForMember"),
    path('send_email/<int:id>', views.send_email, name="send_email"),
    path('review/<int:id>', views.review, name="review"),
    path('edit/<int:id>', views.edit, name="edit"),
    path('view', views.view, name="view"),
]

joinclub/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('comingsoon/', views.comingsoon, name="comingsoon"),
    path('course/', views.course, name="course"),
    #path('admin/', admin.site.urls),
    path('nimda_ognajd/', admin.site.urls), # django_admin倒過來
    path('join/', include('join.urls')),
    path('chart/', include('chart.urls')),
    path('enter/', include('enter.urls')),
    path('api/', include('api.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

handler400 = views.error_400
handler403 = views.error_403
handler404 = views.error_404
handler500 = views.error_500

templates/comingsoon.html
<!doctype html>
<html lang="en">
    <head>
        {% include "favicon.html" %}
        {% include "ga.html" %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
       

        <title>黑客社 - 新生茶會</title>
    </head>

    <body class="text-center bg-dark text-white">
        <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
            <header class="masthead mb-auto">
                <br>
                <div class="inner">
                    <h3>HackerSir</h3>
                    <!--
                        <nav class="nav nav-masthead justify-content-center">
                            <a class="nav-link active" onclick="javascript:outline()">議程</a>
                            <a class="nav-link active" onclick="javascript:tealocation()">地點</a>
                            <a class="nav-link active" onclick="javascript:qrcode()">QRcode</a>
                            <a class="nav-link active" onclick="javascript:rule()">服務條款</a>
                        </nav>
                    -->
                </div>
            </header>
            <main role="main" class="inner cover">
                <br>
                <h1 class="cover-heading">新生茶會</h1>
                <br>
                <p class="lead">2021/09/23  18:30-21:00</p>
                <p class="lead">YouTube 線上直播</p>
                <br>
                <p class="lead" id="btn"></p>
                <p class="lead" id="time"></p>
            </main>
            <footer class="mastfoot mt-auto">
                <div class="inner">
                    <span class="fab fa-facebook-square text-primary mr-2" style="font-size: 3rem;" onclick="javascript:window.open('https://www.facebook.com/HackerSir.tw/')"></span>
                    <span class="fab fa-instagram text-danger mr-2" style="font-size: 3rem;" onclick="javascript:window.open('https://www.instagram.com/fcu_hackersir/')"></span>

                </div>
            </footer>
        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        <!-- 倒數時間 -->
        <script type="text/javascript">
            // Set the date we're counting down to
            var teatime = new Date("September 23, 2021 18:30:00").getTime(); //茶會開始時間(結束倒數)
            var survey = new Date("September 22, 2021 12:00:00").getTime(); //茶會調查結束時間

            var x = setInterval(function() {
                var now = new Date().getTime();

                if (survey - now < 0) { // 茶會調查表單結束提交
                    document.getElementById("btn").innerHTML = '<button class="btn btn-lg btn-secondary" disabled>'+
                                                                    '<i class="fas fa-pray mr-1"></i>'+
                                                                    '茶會報名已截止'+
                                                                '</button>';
                    var distance = teatime - now;
                    if (distance < 0) {
                        clearInterval(x);
                        document.getElementById("btn").innerHTML = '<a href="{% url 'join:join' %}" class="btn btn-lg btn-success">'+
                                                                        '<i class="fas fa-running mr-1"></i>'+
                                                                        '前往入社'+
                                                                    '</a>';
                        document.getElementById("time").innerHTML = '';
                    } else {
                        var days = Math.floor(distance / (1000 * 60 * 60 * 24));
                        var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                        var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
                        var seconds = Math.floor((distance % (1000 * 60)) / 1000);
                        document.getElementById("time").innerHTML = "茶會倒數<br>" + days + " 天 " + hours + " 時 " + minutes + " 分 " + seconds + " 秒";
                    }
                } else { // 茶會調查表單尚未結束提交
                    document.getElementById("btn").innerHTML = '<a href="https://hackersir.kktix.cc/events/2021-freshmenparty" class="btn btn-lg btn-success" target="_blank">'+
                                                                    '茶會報名'+
                                                                '</a>';
                    var distance = survey - now;
                    var days = Math.floor(distance / (1000 * 60 * 60 * 24));
                    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
                    var seconds = Math.floor((distance % (1000 * 60)) / 1000);
                    document.getElementById("time").innerHTML = "茶會報名倒數<br>" + days + " 天 " + hours + " 時 " + minutes + " 分 " + seconds + " 秒";
                }
            }, 1000);
        </script>

        <script type="text/javascript">
            var interval = null;
            $(document).ready(function ($) {
                refresh();
                interval = setInterval("refresh()", 60000); //60秒
            });
            function refresh() {
                $.ajax({
                    url: "{% url 'api:comingsoondata' %}",
                    type: "get",
                    dataType:  "json",
                    success: function(data) {
                        document.getElementById("people").innerHTML = data["Attend_count"];
                    }
                });
            }
        </script>

        <!-- 議程 Modal -->
        <div class="modal fade text-left text-dark" id="outlineModal" tabindex="-1" role="dialog" aria-labelledby="outlineModalTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="outlineModalTitle">議程</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>18:30 - 19:00 入場</p>
                        <p>19:00 - 19:05 開場影片</p>
                        <p>19:05 - 19:15 AIoT 環境空間介紹</p>
                        <p>19:17 - 19:25 社團介紹</p>
                        <p>19:25 - 19:30 幹部介紹</p>
                        <p>19:30 - 19:35 課程規劃</p>
                        <p>19:35 - 19:45 黑科技介紹 從遊戲外掛中談資安技術</p>
                        <p>19:45 - 19:50 年度活動預告</p>
                        <p>19:50 - 19:55 大合照</p>
                        <p>19:55 - 20:30 入社申請 & 茶敘</p>
                        <p>20:30 - 20:40 黑科技介紹 按鍵精靈與網頁爬蟲的異曲同工之妙</p>
                        <p>20:40 - 20:50 黑科技介紹 駭客思維運用於現實中的秘訣與注意事項</p>
                        <p>20:50 - 20:55 友社宣傳</p>
                        <p>20:55 - 21:10 END</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" data-dismiss="modal">
                            <i class="far fa-thumbs-up"></i>
                            確認
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <!-- Rule Modal -->
        <div class="modal fade text-left text-dark" id="ruleModal" tabindex="-1" role="dialog" aria-labelledby="ruleModalTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="ruleModalTitle">服務條款</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <ol>
                            <li>您不得「干擾」或「影響」本站的運行，若經發現，本站有權終止您的使用</li>
                            <li>本站會儲存使用者的資料，所有資料僅供本社入社申請核對使用，您可以要求刪除您的資料，但此舉將會影響您的社員權益</li>
                            <li>本站圖表之資料由使用者在本站所填之資料及<a class="text-primary" href="https://checkin.hackersir.org/" target="_blank">逢甲社博集點</a>之資料，所有資料皆不會對外提供，僅用於統計圖表展示</li>
                        </ol> 
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" data-dismiss="modal">
                            <i class="far fa-thumbs-up"></i>
                            確認
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <!-- QRcode Modal -->
        <div class="modal fade text-left text-dark" id="qrcodeModal" tabindex="-1" role="dialog" aria-labelledby="qrcodeModalTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="qrcodeModalTitle">QRcode</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        {% include "qrcode.html" %}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" data-dismiss="modal">
                            <i class="far fa-thumbs-up"></i>
                            確認
                        </button>
                    </div>
                </div>
            </div>
        </div>
        
        <!-- 地點 Modal -->
        <div class="modal fade text-left text-dark" id="tealocationModal" tabindex="-1" role="dialog" aria-labelledby="tealocationModalTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="tealocationModalTitle">茶會地點</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        {% include "location.html" %}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" data-dismiss="modal">
                            <i class="far fa-thumbs-up"></i>
                            確認
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <script type="text/javascript">
            function outline() {
                $('#outlineModal').modal();
            } 
            function tealocation() {
                $('#tealocationModal').modal();
            } 
            function qrcode() {
                $('#qrcodeModal').modal();
            }
            function rule() {
                $('#ruleModal').modal();
            }
        </script>

        {% include "message.html" %}
    </body>
</html>


templates/ga.html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-147137585-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-147137585-2');
</script>

templates/message.html
{% if messages %}
    {% for message in messages %}
        {% comment %} 茶會調查表單提交成功 {% endcomment %}
        {% ifequal message.tags "attendform success" %}
            <!-- 茶會調表查表單提交成功訊息 -->
            <div class="modal fade text-left text-dark" id="attendModal" tabindex="-1" role="dialog" aria-labelledby="attendModalTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="attendModalTitle">{{ message }}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <ul>
                            　  <li>茶會時間為 2021/09/23</li>
                                <li>18:30 開始入場，19:00 準時開始</li>
                                <li>有任何問題請洽 <a class="text-primary" href="https://www.facebook.com/HackerSir.tw/" target="_blank">逢甲大學黑客社粉絲專頁</a></li>
                            </ul>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-success" data-dismiss="modal">
                                <i class="fas fa-kiss-wink-heart"></i>
                                確認
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                $('#attendModal').modal();
            </script>
        {% endifequal %}

        {% comment %} 入社表單提交成功 {% endcomment %}
        {% ifequal message.tags "joinform success" %}
            <!-- 入社表單提交成功訊息 -->
            <div class="modal fade" id="joinModal" tabindex="-1" role="dialog" aria-labelledby="joinModalTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="joinModalTitle">{{ message }}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <h5>線上入社 & 線上茶會入社之注意事項</h5>
                            <ul>
                                <li>填寫入社表單前，請務必確認匯款至正確的帳戶，並於填表時提供您的銀行帳戶後五碼；匯款完成後，請自行保留匯款收據等相關資訊以供備查。</li>
                                <li>本社確認填表資料及款項入帳無誤後，將於七天內以 E-mail 的方式寄送收據。</li>
                                <li>若七天後未收到收據，請先自行線上查詢是否繳費，如有問題請聯絡黑客社粉絲專頁。</li>
                                <li>如填表後發現資料錯誤，請聯絡黑客社粉絲專頁。</li>
                            </ul>
                            <br>
                            <h5>實體社課入社之注意事項</h5>
                            <ul>
                                <li>每次社課結束後皆可繳納社費，為使作業順利，請先填寫表單後再找事務部部員繳納社費。</li>
                                <li>當事務部部員確認填表資料、繳費資訊無誤以及確認收到款項後，將立刻以 E-mail 的方式寄送收據。</li>
                                <li>如填表後發現資料錯誤，請在繳費時告知你的姓名或學號；若是學號填錯，請直接重新填寫表單。</li>
                            </ul>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-success" data-dismiss="modal">
                                <i class="fas fa-kiss-wink-heart"></i>
                                確認
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                $('#joinModal').modal();
            </script>
        {% endifequal %}

        {% comment %} 茶會表單調查結束 {% endcomment %}
        {% ifequal message.tags "teatimeform info" %}
            <!-- 表單已結束提交 -->
            <div class="modal fade text-left text-dark" id="teatimeformModal" tabindex="-1" role="dialog" aria-labelledby="teatimeformModalTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="teatimeformModalTitle">{{ message }}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <ul>
                            　  <li>茶會時間為 2021/09/23</li>
                                <li>18:30 開始入場，19:00 準時開始</li>
                                <li>有任何問題請洽 <a class="text-primary" href="https://www.facebook.com/HackerSir.tw/" target="_blank">逢甲大學黑客社粉絲專頁</a></li>
                            </ul>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-success" data-dismiss="modal">
                                <i class="far fa-kiss-wink-heart"></i>
                                確認
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                $('#teatimeformModal').modal();
            </script>
        {% endifequal %}

        {% comment %} 茶會尚未開始 {% endcomment %}
        {% ifequal message.tags "yetstart info" %}
            <!-- 茶會尚未開始 -->
            <div class="modal fade text-left text-dark" id="yetstartModal" tabindex="-1" role="dialog" aria-labelledby="yetstartModalTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="yetstartModalTitle">{{ message }}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <ul>
                            　  <li>茶會時間為 2021/09/23</li>
                                <li>18:30 開始入場，19:00 準時開始</li>
                                <li>有任何問題請洽 <a class="text-primary" href="https://www.facebook.com/HackerSir.tw/" target="_blank">逢甲大學黑客社粉絲專頁</a></li>
                            </ul>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-success" data-dismiss="modal">
                                <i class="far fa-kiss-wink-heart"></i>
                                確認
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                $('#yetstartModal').modal();
            </script>
        {% endifequal %}

        {% comment %} 茶會開始，茶會調查轉址 {% endcomment %}
        {% ifequal message.tags "teatimestart info" %}
            <!-- 茶會開始，茶會調查轉址 -->
            <div class="modal fade text-left text-dark" id="teatimestartModal" tabindex="-1" role="dialog" aria-labelledby="teatimestartModalTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="teatimestartModalTitle">{{ message }}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <ul>
                                <li>有任何問題請洽 <a class="text-primary" href="https://www.facebook.com/HackerSir.tw/" target="_blank">逢甲大學黑客社粉絲專頁</a></li>
                            </ul>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary" data-dismiss="modal">
                                <i class="far fa-kiss-wink-heart"></i>
                                確認
                            </button>
                            <a class="btn btn-success" href="{% url 'join:join' %}" role="button">
                                <i class="fas fa-donate"></i>
                                點我入社
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                $('#teatimestartModal').modal();
            </script>
        {% endifequal %}

    {% endfor %}
{% endif %}

templates/narbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">HackerSir</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        表單
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown1">
                        <!--
                            <a class="dropdown-item" href="{% url 'enter:attend' %}">茶會調查</a>
                            <a class="dropdown-item" href="{% url 'enter:checkin' %}">茶會簽到</a>
                        -->
                        <a class="dropdown-item" href="{% url 'join:join' %}">入社表單</a>
                        <a class="dropdown-item" href="{% url 'join:secret' %}">保密協議</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        查詢
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
                        <!--
                            <a class="dropdown-item" href="{% url 'enter:search' %}">茶會調查</a>
                        -->
                        
                        <a class="dropdown-item" href="{% url 'join:search' %}">入社表單</a>
                        <a class="dropdown-item" href="{% url 'join:secretSearch' %}">保密協議</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'join:view' %}">總覽</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown3" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        統計圖表
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown3">
                        <a class="dropdown-item" href="{% url 'chart:joinclub' %}">入社情形</a>
                        <!--
                            <a class="dropdown-item" href="{% url 'chart:receiveprize' %}">領獎情形</a>
                            <a class="dropdown-item" href="{% url 'chart:attendance' %}">出席情形</a>
                        -->
                    </div>
                </li>
            {% else %}
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'join:join' %}">入社表單</a> 
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'join:secret' %}">保密協議</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        查詢
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
                        <a class="dropdown-item" href="{% url 'join:searchForMember' %}">繳款情形</a>
                    </div>
                </li>
                
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'course' %}">課程總覽</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://act.hackersir.org/" target="_blank" >活動列表</a>
            </li>
        </ul>
        {% if user.is_authenticated %}
            <span class="text-white my-2 mr-2 my-sm-0">Hi {{ user.username }}!</span>
            {% comment %} <a class="btn btn-outline-primary my-2 mr-2 my-sm-0" href="{% url 'admin:index' %}">Admin</a> {% endcomment %}
            <a class="btn btn-outline-light my-2 mr-2 my-sm-0" href="{% url 'logout' %}">登出</a>
        {% comment %} {% else %}
            <a class="btn btn-outline-light my-2 mr-2 my-sm-0" href="{% url 'login' %}">登入</a> {% endcomment %}
        {% endif %}
        {% comment %} <a class="btn btn-outline-light my-2 mr-2 my-sm-0" href="{% url 'register' %}">註冊</a> {% endcomment %}
    </div>
</nav>