api/urls.py
from django.urls import path

from . import views

app_name = 'api'

urlpatterns = [
    path('comingsoondata', views.ComingsoonData.as_view(), name="comingsoondata"),
    path('joinclubdata', views.JoinclubData.as_view(), name="joinclubdata"),
    path('receiveprizedata', views.ReceiveprizeData.as_view(), name="receiveprizedata"),
    path('attendancedata', views.AttendanceData.as_view(), name="attendancedata"),
]

chart/urls.py
from django.urls import path

from . import views

app_name = 'chart'

urlpatterns = [
    path('joinclub', views.joinclub, name="joinclub"),
    path('receiveprize', views.receiveprize, name="receiveprize"),
    path('attendance', views.attendance, name="attendance"),
    path('export_all', views.export_all, name="export_all"),
    path('export_NP', views.export_NP, name="export_NP"),
    path('export_M', views.export_M, name="export_M"),
    path('export_secret', views.export_secret, name="export_secret"),
]

enter/urls.py
from django.urls import path

from . import views

app_name = 'enter'

urlpatterns = [
    path('attend', views.attend, name="attend"),
    path('search', views.search, name="search"),
    path('edit/<int:id>', views.edit, name="edit"),
    path('checkin', views.checkin, name="checkin"),
    path('prize/<str:nid>', views.prize, name="prize"),
]

joinclub/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('comingsoon/', views.comingsoon, name="comingsoon"),
    path('course/', views.course, name="course"),
    #path('admin/', admin.site.urls),
    path('nimda_ognajd/', admin.site.urls), # django_admin倒過來
    path('join/', include('join.urls')),
    path('chart/', include('chart.urls')),
    path('enter/', include('enter.urls')),
    path('api/', include('api.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

handler400 = views.error_400
handler403 = views.error_403
handler404 = views.error_404
handler500 = views.error_500

enter/models.py
from django.db import models

class Attend(models.Model):
    name = models.CharField(max_length=50)
    nid = models.CharField(max_length=15, unique=True)

    def __str__(self):
        return "%s %s" % (self.nid, self.name)

class Checkin(models.Model):
    STATUS_CHOICES = [
        ('NO', '無法領獎'), 
        ('YET', '尚未領獎'),
        ('TIX', '已使用票券領獎'),
        ('FORM', '已填表單領獎'),
        ('MIX', '已填表單加使用票券領獎'),
    ]

    nid = models.CharField(max_length=15, unique=True)
    status = models.CharField(max_length=4, choices=STATUS_CHOICES, default="NO")

    def __str__(self):
        return "%s [%s]" % (self.nid, self.get_status_display())

enter/forms.py
from django import forms
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _
from .models import Attend, Checkin

class AttendForm(ModelForm):
    class Meta:
        model = Attend
        fields = ['name', 'nid']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '請輸入姓名'}),
            'nid': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '請輸入學號'})
        }
        labels = {
            'name': _('姓名'),
            'nid': _('學號'),
        }
        error_messages = {
            'name': {
                'required': _('必須填寫姓名'),
                'max_length': _('你的姓名太長囉'),
            },
            'nid': {
                'required': _('必須填寫學號'),
                'unique': _('您的學號已經被使用過囉'),
                'max_length': _('你的學號太長囉'),
            },
        }

class CheckinForm(ModelForm):
    class Meta:
        model = Checkin
        fields = ['nid']
        widgets = {
            'nid': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '請輸入欲簽到學號'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
        }
        labels = {
            'nid': _('學號'),
            'status': _('領獎狀態'),
        }
        error_messages = {
            'nid': {
                'required': _('必須填寫學號'),
                'unique': _('您的學號已經簽到'),
                'max_length': _('你的學號太長囉'),
            },
            'status': {
                'invalid_choice': _('請勿亂來'),
            },
        }

enter/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import AttendForm, CheckinForm
from .models import Attend, Checkin

def attend(request):
    if request.method == 'POST':
        form = AttendForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, '提交成功', extra_tags='attendform')
            return HttpResponseRedirect(reverse('commingsoon'))
    else:
        form = AttendForm()
    return render(request, 'attend.html', {'form': form})

@login_required
def search(request):
    if request.method == 'POST':
        nid = request.POST.get('nid')
        name = request.POST.get('name')
        if nid:
            try:
                attend = Attend.objects.get(nid=nid)
                return render(request, 'enter_search.html', {'attend': attend})
            except Attend.DoesNotExist:
                return render(request, 'enter_search.html', {})
        elif name:
            try:
                attend = Attend.objects.get(name=name)
                return render(request, 'enter_search.html', {'attend': attend})
            except Attend.DoesNotExist:
                return render(request, 'enter_search.html', {})
    return render(request, 'enter_search.html', {})

@login_required
def edit(request, id):
    attend = get_object_or_404(Attend, id=id)
    if request.method == 'POST':
        form = AttendForm(request.POST, instance=attend)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('index'))
        else:
            return render(request, 'enter_edit.html', {'form': form, 'attend': attend})
    else:
        form = AttendForm()
    return render(request, 'enter_edit.html', {'form': form, 'attend': attend})

@login_required
def checkin(request):
    if request.method == 'POST':
        form = CheckinForm(request.POST)
        if form.is_valid():
            nid = form.cleaned_data['nid']
            if Attend.objects.filter(nid=nid).exists(): # status = 尚未領獎
                obj = form.save(commit=False)
                obj.status = 'YET'
                obj.save()
            else: # status = 無法領獎
                form.save()
            return HttpResponseRedirect(reverse('enter:prize', args=[nid]))
        else:
            return render(request, 'checkin.html', {'form': form})
    else:
        form = CheckinForm()
    return render(request, 'checkin.html', {'form': form})

@login_required
def prize(request, nid):
    attend = get_object_or_404(Checkin, nid=nid)
    if request.method == 'POST':
        if attend.status == 'NO' and ('tix' in request.POST):
            attend.status = 'TIX'
            attend.save()
        elif attend.status == 'YET':
            if 'confirm' in request.POST:
                attend.status = 'FORM'
                attend.save()
            elif 'mix' in request.POST:
                attend.status = 'MIX'
                attend.save()
    return render(request, 'prize.html', {'attend': attend})

def review(request, id):
    member = get_object_or_404(Member, id=id)
    if request.method == 'POST':
        if member.status == 'UR':
            member.status = 'NP'
            member.save()
        elif member.status == 'NP':
            member.status = 'M'
            member.save()
    return render(request, 'review.html', {'member': member})

enter/templates/attend.html
{% extends "layout.html" %}

{% block head %}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.1/css/all.css" integrity="sha384-wxqG4glGB3nlqX0bi23nmgwCSjWIW13BdLUEYC4VIMehfbcro/ATkyDsF/AbIOVe" crossorigin="anonymous">
{% endblock %}

{% block title %}黑客社 - 茶會出席調查{% endblock %}

{% block content %}
<div class="container">
    <h3>茶會出席調查</h3>
    <hr>
    <form action="{% url 'enter:attend' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ form.name.label_tag }}
            {{ form.name }}
            {% comment %} 錯誤訊息 {% endcomment %}
            {% if form.name.errors %}
                {% for error in form.name.errors %}
                    <div class="invalid-feedback">
                        <p>{{ error }}</p>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.nid.label_tag }}
            {{ form.nid }}
            {% comment %} 錯誤訊息 {% endcomment %}
            {% if form.nid.errors %}
                {% for error in form.nid.errors %}
                    <div class="invalid-feedback">
                        <p>{{ error }}</p>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <div class="custom-control custom-checkbox my-3">
            <input type="checkbox" class="custom-control-input" id="privacy" name="privacy" required>
            <label class="custom-control-label" for="privacy" style="color:red">本人已閱讀完注意事項並同意將個人資料提供逢甲大學黑客社使用，本社依個人資料保護法、相關法規及學校相關法規進行處理以及利用。</label>
        </div>
        <button type="submit" class="btn btn-primary">
            <i class="far fa-check-circle"></i>
            提交
        </button>
        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#attendModal">
            <i class="fab fa-readme"></i>
            點我再次閱讀注意事項
        </button>
    </form>
</div>
<!-- 入社表單注意事項 -->
<div class="modal fade" id="attendModal" tabindex="-1" role="dialog" aria-labelledby="attendModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="attendModalTitle">茶會出席調查注意事項</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <ol>
                    <li>為了提供您更舒適的場地，請填寫此表單以利本社調查茶會總出席人數</li>
                    <li>茶會時間: 2019/09/17，<span style="color:red">18:30 開始入場</span>，地點在科航八樓</li>
                    <li>若茶會當天要入社，請攜帶 200 元社費及學生證</li>
                    <li>若您不小心填寫錯誤資訊或有任何問題，請洽<a href="https://www.facebook.com/HackerSir.tw/">逢甲大學黑客社粉專</a>，您無法自己更改資訊</li>
                </ol>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal">
                    <i class="fas fa-book"></i>
                    我已閱讀完注意事項
                </button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
    $('#attendModal').modal();

    {% if form.name.errors %}
        document.getElementById("id_name").classList.add("is-invalid");
    {% endif %}
    {% if form.nid.errors %}
        document.getElementById("id_nid").classList.add("is-invalid");
    {% endif %}
</script>
{% endblock %}

enter/templates/checkin.html
{% extends "layout.html" %}

{% block head %}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.1/css/all.css" integrity="sha384-wxqG4glGB3nlqX0bi23nmgwCSjWIW13BdLUEYC4VIMehfbcro/ATkyDsF/AbIOVe" crossorigin="anonymous">
{% endblock %}

{% block title %}黑客社 - 茶會簽到{% endblock %}

{% block content %}
<div class="container">
    <div class="row d-flex justify-content-between">
        <div class="col-auto">
            <h3>茶會簽到</h3>
        </div>
    </div>
    <hr>

    {% comment %} 錯誤訊息 {% endcomment %}
    {% if form.nid.errors %}
        {% for error in form.nid.errors %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{ error }} <a href="{% url 'enter:prize' nid=form.nid.value %}" class="alert-link">點此前往領獎頁面</a>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}

    <form action="{% url 'enter:checkin' %}" method="POST">
        {% csrf_token %}
        <div class="form-row align-items-center">
            <div class="col-auto mr-4">
                <label class="sr-only" for="id_nid">NID</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text">學號</div>
                    </div>
                    {{ form.nid }}
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-outline-secondary">
                            <i class="fas fa-user-edit"></i>
                            簽到
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

enter/templates/enter_edit.html
{% extends "layout.html" %}

{% block title %}黑客社 - 修改茶會調查表單{% endblock %}

{% block content %}
<div class="container">
    <h3>修改茶會調查表單</h3>
    <hr>
    <form action="{% url 'enter:edit' id=attend.id %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ form.name.label_tag }}
            <input type="text" name="name" class="form-control" value="{{ attend.name }}" placeholder="請輸入姓名" maxlength="50" required id="id_name">
            {% comment %} 錯誤訊息 {% endcomment %}
            {% if form.name.errors %}
                {% for error in form.name.errors %}
                    <div class="invalid-feedback">
                        <p>{{ error }}</p>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.nid.label_tag }}
            <input type="text" name="nid" class="form-control" value="{{ attend.nid }}" placeholder="請輸入學號" maxlength="15" required id="id_nid">
            {% comment %} 錯誤訊息 {% endcomment %}
            {% if form.nid.errors %}
                {% for error in form.nid.errors %}
                    <div class="invalid-feedback">
                        <p>{{ error }}</p>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <div class="custom-control custom-checkbox my-3">
            <input type="checkbox" class="custom-control-input" id="privacy" name="privacy" required>
            <label class="custom-control-label" for="privacy" style="color:red">本人同意將個人資料提供逢甲大學黑客社使用，本社依個人資料保護法、相關法規及學校相關法規進行處理以及利用。</label>
        </div>
        <button type="submit" class="btn btn-primary">提交</button>
    </form>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
    {% if form.name.errors %}
        document.getElementById("id_name").classList.add("is-invalid");
    {% endif %}
    {% if form.nid.errors %}
        document.getElementById("id_nid").classList.add("is-invalid");
    {% endif %}
</script>
{% endblock %}

enter/templates/enter_search.html
{% extends "layout.html" %}

{% block head %}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.1/css/all.css" integrity="sha384-wxqG4glGB3nlqX0bi23nmgwCSjWIW13BdLUEYC4VIMehfbcro/ATkyDsF/AbIOVe" crossorigin="anonymous">
{% endblock %}

{% block title %}黑客社 - 查詢(茶會調查){% endblock %}

{% block content %}
<div class="container">
    <div class="row d-flex justify-content-between">
        <div class="col-auto">
            <h3>茶會調查 - 查詢</h3>
        </div>
        <div class="btn-group col-auto">
            <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                匯出 CSV
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'chart:export_all' %}">全部</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'chart:export_M' %}">已繳費</a>
                <a class="dropdown-item" href="{% url 'chart:export_NP' %}">未繳費</a>
            </div>
        </div>
    </div>
    
    <hr>
    <form action="{% url 'enter:search' %}" method="POST">
        {% csrf_token %}
        <div class="form-row align-items-center">
            <div class="col-auto mr-4">
                <label class="sr-only" for="nid">NID</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text">學號</div>
                    </div>
                    <input type="text" class="form-control" id="nid" placeholder="請輸入欲查詢學號" name="nid">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-outline-secondary">
                            <i class="fas fa-search"></i>
                            查詢
                        </button>
                    </div>
                </div>
            </div>
            <div class="col-auto my-4">
                <label class="sr-only" for="name">Name</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text">姓名</div>
                    </div>
                    <input type="text" class="form-control" id="name" placeholder="請輸入欲查詢姓名" name="name">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-outline-secondary">
                            <i class="fas fa-search"></i>
                            查詢
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>

    {% if attend %}
    <hr>
    <div class="card">
        <h5 class="card-header">
            <div class="row justify-content-between">
                <div class="col-auto">
                    {{ attend.nid }} - 茶會出席資料
                </div>
            </div>
        </h5>
        <div class="card-body">
            <p class="card-text">姓名：{{ attend.name }}</p>
            <p class="card-text">學號：{{ attend.nid }}</p>
        </div>
        <div class="card-footer">
            <a href="{% url 'enter:edit' id=attend.id %}" class="btn btn-primary" role="button">
                <i class="far fa-edit"></i>
                修改資料
            </a>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

enter/templates/prize.html
{% extends "layout.html" %}

{% block head %}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.1/css/all.css" integrity="sha384-wxqG4glGB3nlqX0bi23nmgwCSjWIW13BdLUEYC4VIMehfbcro/ATkyDsF/AbIOVe" crossorigin="anonymous">
{% endblock %}

{% block title %}黑客社 - 領獎{% endblock %}

{% block content %}
<div class="container">
    <h3>領獎</h3>
    <hr>
    <div class="card">
        <h5 class="card-header">
            <div class="row justify-content-between">
                <div class="col-auto">
                    {{ attend.nid }} - 資料
                </div>
                <div class="col-auto">
                    {% comment %} 無法領獎 {% endcomment %}
                    {% ifequal attend.status "NO" %}
                        <span class="badge badge-pill badge-danger">
                            {{ attend.get_status_display }}
                        </span>
                    {% endifequal %}
                    {% comment %} 尚未領獎 {% endcomment %}
                    {% ifequal attend.status "YET" %}
                        <span class="badge badge-pill badge-warning">
                            {{ attend.get_status_display }}
                        </span>
                    {% endifequal %}
                    {% comment %} 已使用票券領獎 {% endcomment %}
                    {% ifequal attend.status "TIX" %}
                        <span class="badge badge-pill badge-success">
                            {{ attend.get_status_display }}
                        </span>
                    {% endifequal %}
                    {% comment %} 已填表單領獎 {% endcomment %}
                    {% ifequal attend.status "FORM" %}
                        <span class="badge badge-pill badge-success">
                            {{ attend.get_status_display }}
                        </span>
                    {% endifequal %}
                    {% comment %} 已填表單加使用票券領獎 {% endcomment %}
                    {% ifequal attend.status "MIX" %}
                        <span class="badge badge-pill badge-primary">
                            {{ attend.get_status_display }}
                        </span>
                    {% endifequal %}
                </div>
            </div>
        </h5>
        <div class="card-body">
            <p class="card-text">學號：{{ attend.nid }}</p>
            <p class="card-text">領獎狀態：{{ attend.get_status_display }}</p>
        </div>
        <div class="card-footer">
            <div class="row justify-content-between">
                <form class="form-inline col-auto" action="{% url 'enter:prize' nid=attend.nid %}" method="POST">
                    {% csrf_token %}
                    {% comment %} 無法領獎 {% endcomment %}
                    {% ifequal attend.status "NO" %}
                        <button type="submit" class="btn btn-warning mr-1" name="tix">
                            <i class="fas fa-tag"></i>
                            使用票券領獎
                        </button>
                    {% endifequal %}
                    {% comment %} 尚未領獎 {% endcomment %}
                    {% ifequal attend.status "YET" %}
                        <button type="submit" class="btn btn-success mr-1" name="confirm">
                            <i class="fas fa-gift"></i>
                            確認領獎
                        </button>
                        <button type="submit" class="btn btn-info mr-1" name="mix">
                            <i class="fas fa-hand-holding-heart"></i>
                            確認領獎加有帶票券
                        </button>
                    {% endifequal %}
                </form>
                <a href="{% url 'enter:checkin' %}" class="btn btn-primary col-auto" role="button">
                    <i class="fas fa-reply"></i>
                    返回簽到頁面
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}